-- Add columns to hearth.houses for the generated-illustration placeholder.
--
-- The dashboard shows a stylized architectural sketch in place of a real
-- photo until the user uploads their own. The sketch is generated by the
-- image step appended to the Day One Briefing pipeline (see
-- workflows/house-image.ts) and lives in the `house-images` Supabase
-- Storage bucket at `{house_id}/generated-sketch.png`.
--
-- generated_image_url holds the STORAGE PATH within that bucket, not a
-- public URL — the bucket is private (see the companion storage RLS
-- migration). The dashboard derives a signed URL at render time via
-- lib/house-image/signed-url.ts.
--
-- generated_image_prompt is the literal prompt string handed to the image
-- model, preserved so regenerations can be compared and so we have an
-- audit trail of what we asked for if a generation produces a surprising
-- result.
--
-- generated_image_created_at moves on every successful regeneration. Null
-- until the first generation lands.

alter table hearth.houses
  add column generated_image_url text,
  add column generated_image_prompt text,
  add column generated_image_created_at timestamptz;
